# Generated by Django 3.1.6 on 2021-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
