# Generated by Django 3.1.6 on 2021-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210209_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
