# Generated by Django 3.1.6 on 2021-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210210_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
